l1=[1,5,6]
l2=[2,3,4,7,8,9]
l=[]
i=0
j=0
n1=len(l1)
n2=len(l2)
while(i<n1 and j<n2):
    if(l1[i]<l2[j]):
        l.append(l1[i])
        i=i+1
    else:
        l.append(l2[j])
        j=j+1
if(i<n1):
    while(i<n1):
        l.append(l1[i])
        i=i+1
else:
    while(j<n2):
        l.append(l2[j])
        j=j+1
print(l)